name: Tests
on: 
  push:
    branches:
      - '*'
 
jobs:
    tests:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@master

            - name: Build container image
              run: |
                  make build

            - name: Start database used in the tests
              run: |
                  make database

            - name: Wait some seconds to the database start to accept connections
              run: |
                  sleep 30s

            - name: Run tests
              run: |
                  make test

